"""Visualization functions.

Every figure shown in the notebook, the Streamlit app, and the site is
generated by a function in this module. This guarantees that the three
presentations are identical: one source of truth, three presentations.

All functions return a ``plotly.graph_objects.Figure``. They never call
``.show()``; displaying is the caller's responsibility. The pyvis
genealogy graph is the only exception, and it is imported lazily to
keep the base install light.

Plotly figures are pure Python objects and can be tested for structure
without rendering, which is what ``tests/test_visualize.py`` does.
"""

from __future__ import annotations

import plotly.graph_objects as go

from aletheia.evaluation import ThreadResult, summarize_results

# ---------------------------------------------------------------------------
# Shared styling
# ---------------------------------------------------------------------------

_ALETHEIA_COLOR = "#1f77b4"
_BASELINE_COLOR = "#d62728"
_NEUTRAL_COLOR = "#7f7f7f"


def _base_layout(title: str, xaxis: str, yaxis: str) -> dict:
    return {
        "title": {"text": title, "x": 0.5, "xanchor": "center"},
        "xaxis": {"title": xaxis},
        "yaxis": {"title": yaxis},
        "template": "plotly_white",
        "margin": {"l": 60, "r": 30, "t": 60, "b": 60},
    }


# ---------------------------------------------------------------------------
# Figure 1 — Median relative error comparison
# ---------------------------------------------------------------------------


def figure_median_error_comparison(results: list[ThreadResult]) -> go.Figure:
    """Bar chart of median relative error for Aletheia and each baseline.

    Lower is better. Aletheia's bar is highlighted in a distinct color.
    """
    summary = summarize_results(results)
    aletheia = summary["aletheia"]
    baselines = summary["baselines"]

    names = ["Aletheia"] + sorted(baselines.keys())
    values = [aletheia.get("median_relative_error", 0.0)] + [
        baselines[name]["median_relative_error"] for name in sorted(baselines.keys())
    ]
    colors = [_ALETHEIA_COLOR] + [_BASELINE_COLOR] * (len(names) - 1)

    fig = go.Figure(
        data=[
            go.Bar(
                x=names,
                y=values,
                marker_color=colors,
                text=[f"{v:.3f}" for v in values],
                textposition="auto",
            )
        ]
    )
    fig.update_layout(
        **_base_layout(
            "Median relative error on inflation factor I",
            "Method",
            "Median relative error (lower is better)",
        )
    )
    return fig


# ---------------------------------------------------------------------------
# Figure 2 — ARI / NMI comparison
# ---------------------------------------------------------------------------


def figure_clustering_quality(results: list[ThreadResult]) -> go.Figure:
    """Grouped bar chart of median ARI and NMI for each method."""
    summary = summarize_results(results)
    aletheia = summary["aletheia"]
    baselines = summary["baselines"]

    methods = ["Aletheia"] + sorted(baselines.keys())
    ari_values = [aletheia.get("median_ari", 0.0)] + [
        baselines[name]["median_ari"] for name in sorted(baselines.keys())
    ]
    nmi_values = [aletheia.get("median_nmi", 0.0)] + [
        baselines[name]["median_nmi"] for name in sorted(baselines.keys())
    ]

    fig = go.Figure(
        data=[
            go.Bar(name="ARI", x=methods, y=ari_values, marker_color=_ALETHEIA_COLOR),
            go.Bar(
                name="NMI", x=methods, y=nmi_values, marker_color=_NEUTRAL_COLOR
            ),
        ]
    )
    fig.update_layout(
        **_base_layout(
            "Clustering quality: ARI and NMI",
            "Method",
            "Score (higher is better)",
        ),
        barmode="group",
    )
    return fig


# ---------------------------------------------------------------------------
# Figure 3 — Per-thread error distribution
# ---------------------------------------------------------------------------


def figure_per_thread_errors(results: list[ThreadResult]) -> go.Figure:
    """Box plot of relative error per thread, for Aletheia and each baseline."""
    aletheia_errors = [r.aletheia.relative_error_inflation for r in results]

    traces = [
        go.Box(
            y=aletheia_errors,
            name="Aletheia",
            marker_color=_ALETHEIA_COLOR,
            boxmean="sd",
        )
    ]

    baseline_names = sorted({name for r in results for name in r.baselines})
    for name in baseline_names:
        errors = [r.baselines[name].relative_error_inflation for r in results]
        traces.append(
            go.Box(
                y=errors,
                name=name,
                marker_color=_BASELINE_COLOR,
                boxmean="sd",
            )
        )

    fig = go.Figure(data=traces)
    fig.update_layout(
        **_base_layout(
            "Per-thread relative error distribution",
            "Method",
            "Relative error (lower is better)",
        )
    )
    return fig


# ---------------------------------------------------------------------------
# Figure 4 — Predicted vs true inflation
# ---------------------------------------------------------------------------


def figure_inflation_scatter(results: list[ThreadResult]) -> go.Figure:
    """Scatter of predicted vs true inflation factor, with the identity line.

    Points on the diagonal are perfect estimates. Points above the
    diagonal mean the method underestimates plurality (predicts too few
    clusters); below means it overestimates.
    """
    true_vals = [r.true_inflation for r in results]
    aletheia_vals = [r.aletheia.inflation_predicted for r in results]

    traces: list[go.Scatter] = [
        go.Scatter(
            x=true_vals,
            y=aletheia_vals,
            mode="markers",
            name="Aletheia",
            marker={"color": _ALETHEIA_COLOR, "size": 10},
        )
    ]

    baseline_names = sorted({name for r in results for name in r.baselines})
    for name in baseline_names:
        vals = [r.baselines[name].inflation_predicted for r in results]
        traces.append(
            go.Scatter(
                x=true_vals,
                y=vals,
                mode="markers",
                name=name,
                marker={"color": _BASELINE_COLOR, "size": 6, "opacity": 0.6},
            )
        )

    if true_vals:
        lo = min(true_vals) * 0.8
        hi = max(true_vals) * 1.2
        traces.append(
            go.Scatter(
                x=[lo, hi],
                y=[lo, hi],
                mode="lines",
                name="Perfect estimate",
                line={"color": _NEUTRAL_COLOR, "dash": "dash"},
            )
        )

    fig = go.Figure(data=traces)
    fig.update_layout(
        **_base_layout(
            "Predicted vs true inflation factor",
            "True I",
            "Predicted I",
        )
    )
    return fig


# ---------------------------------------------------------------------------
# Figure 5 — Improvement over best baseline
# ---------------------------------------------------------------------------


def figure_improvement_gauge(results: list[ThreadResult]) -> go.Figure:
    """Single-bar chart of Aletheia's relative improvement over the best baseline.

    Positive values (green) mean Aletheia wins. Negative values (red)
    mean Aletheia loses. Zero means no contribution.
    """
    summary = summarize_results(results)
    improvement = summary["improvement_over_best_baseline"]
    color = "#2ca02c" if improvement > 0 else "#d62728"

    fig = go.Figure(
        data=[
            go.Bar(
                x=["Aletheia vs best baseline"],
                y=[improvement],
                marker_color=color,
                text=[f"{improvement:+.1%}"],
                textposition="auto",
            )
        ]
    )
    fig.update_layout(
        **_base_layout(
            "Relative improvement over best baseline",
            "",
            "Relative improvement",
        )
    )
    fig.update_yaxes(tickformat=".0%")
    return fig


# ---------------------------------------------------------------------------
# Figure 6 — Argument genealogy (pyvis, lazy import)
# ---------------------------------------------------------------------------


def figure_genealogy_pyvis(
    comments: list[str],
    labels: list[int],
    output_html: str = "genealogy.html",
) -> str:
    """Render a pyvis network of the argument genealogy and save it to HTML.

    Nodes are comments, colored by their cluster label. Only edges
    within the same cluster are drawn (to keep the graph readable).

    Args:
        comments: The comment strings.
        labels: Cluster labels, one per comment.
        output_html: Path of the HTML file to write.

    Returns:
        The path to the written HTML file.

    Raises:
        ImportError: If ``pyvis`` is not installed. Install with
            ``pip install -e ".[viz]"``.
    """
    try:
        from pyvis.network import Network
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "pyvis is required for the genealogy graph. "
            'Install with: pip install -e ".[viz]"'
        ) from exc

    net = Network(height="600px", width="100%", notebook=False)
    palette = [
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#7f7f7f",
        "#bcbd22",
        "#17becf",
    ]

    for i, (comment, label) in enumerate(zip(comments, labels, strict=True)):
        short = comment if len(comment) <= 60 else comment[:57] + "..."
        net.add_node(
            i,
            label=short,
            color=palette[label % len(palette)],
            title=comment,
        )

    for i in range(len(comments)):
        for j in range(i + 1, len(comments)):
            if labels[i] == labels[j]:
                net.add_edge(i, j)

    net.write_html(output_html, notebook=False)
    return output_html